### PR TITLE
Remove version number from the module name

### LINKED ISSUE #27: Suggestion: Rename module from "Doctrine2" to "Doctrine"
With Doctrine 3 on its way, I think it's about time to start thinking about removing the version number "2" from this module's name, to prevent the (hopefully false) impression that it doesn't work with Doctrine 3.

### PR DESCRIPTION
**Pull request by TavoNiievez**
Closes #27

### CODE REVIEW

**Comment by W0rma** [comment]
@TavoNiievez Thank you for all the work - I tested this new repository in one of my projects and it worked fine.

The new package `codeception/module-doctrine` is not available on packagist yet (https://packagist.org/packages/codeception/).

**Comment by TavoNiievez** [comment]
@W0rma I already talked to @DavertMik about this via Slack. I don't have permissions to publish it myself.

**Comment by TavoNiievez** [comment]
@W0rma it is already published, thank you.

**Comment by W0rma** [comment]
@TavoNiievez That's great. Thank you!

**Pull request merged**
